#!/usr/bin/env python3
"""Capture page images from a DocSend dataroom, space, or single document.

Drives a real Chromium session through the DocSend email gate, enumerates every
document in the room, and saves one image file per page plus a manifest.json
that build_docx.py / export_to_notes.py consume.

Three capture strategies, tried in order of fidelity and cost:
  1. page_data  - DocSend's own JSON endpoint returns a signed URL for the
                  full-resolution page image. Cheapest and sharpest: no
                  rendering, no compositing, bytes straight to disk.
  2. dom        - Read the <img> the viewer is displaying and download those
                  bytes. Used when page_data is unavailable or blocked.
  3. screenshot - Screenshot the page element. Last resort; it is the only one
                  that works when pages are canvas-rendered, but it captures
                  at viewport resolution, so text is softer.

Usage:
    python3 capture_dataroom.py <url> --email you@example.com [options]

Only use this on rooms that have been shared with you. Captured pages carry
whatever watermark DocSend stamps for your viewer email.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import time
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin, urlparse

try:
    from playwright.async_api import async_playwright
except ImportError:  # pragma: no cover - environment guard
    sys.exit(
        "playwright is not installed. Run:\n"
        "  python3 -m pip install playwright python-docx pillow\n"
        "  python3 -m playwright install chromium"
    )


# Three URL shapes matter, and conflating them is the classic way to find zero
# documents in a room that plainly has them:
#   /view/<id>                      a standalone document
#   /view/s/<space-id>              the space (dataroom) itself — not a document
#   /view/s/<space-id>/d/<doc-id>   a document *inside* a space
# The third is what a space's own file list links to, so it has to be recognised
# even though it also begins with /view/s/. Check it first for that reason.
# A document inside a space is /view/<space>/d/<doc>, and the space segment may
# or may not carry the s/ prefix — both forms are in the wild, and the one
# without it is easy to mistake for a standalone /view/<id> document, which
# silently collapses every document in the room into a single phantom entry.
SPACE_DOC_RE = re.compile(r"/view/(?:s/)?[A-Za-z0-9_-]+/d/([A-Za-z0-9_-]{4,})")
STANDALONE_DOC_RE = re.compile(r"/view/(?!s/)([A-Za-z0-9_-]{6,})")
SPACE_ID_RE = re.compile(r"/view/(?:s/)?([A-Za-z0-9_-]{6,})")

# Paths quoted inside the page's own scripts. A single-page room ships its file
# list as JSON and renders rows with click handlers, leaving no anchors to crawl,
# so the paths have to be read out of the payload instead.
EMBEDDED_PATH_RE = re.compile(r"""["'](/(?:view|d)/[A-Za-z0-9_\-/]{4,})["']""")


def doc_match(path: str) -> tuple[str, str] | None:
    """Return (doc_id, canonical path) if this path addresses a document."""
    m = SPACE_DOC_RE.search(path)
    if m:
        return m.group(1), m.group(0)
    m = STANDALONE_DOC_RE.search(path)
    if m:
        return m.group(1), f"/view/{m.group(1)}"
    return None

PAGE_COUNT_PATTERNS = [
    re.compile(r'"?total_pages"?\s*[:=]\s*"?(\d+)', re.I),
    re.compile(r'"?page_count"?\s*[:=]\s*"?(\d+)', re.I),
    re.compile(r'"?pageCount"?\s*[:=]\s*"?(\d+)', re.I),
    re.compile(r'data-total-pages="(\d+)"', re.I),
    re.compile(r'data-page-count="(\d+)"', re.I),
]

EMAIL_SELECTORS = [
    "#link_auth_form_email",
    'input[name="link_auth_form[email]"]',
    'input[type="email"]',
    'input[name*="email" i]',
    'input[placeholder*="email" i]',
]
PASSCODE_SELECTORS = [
    "#link_auth_form_passcode",
    'input[name="link_auth_form[passcode]"]',
    'input[type="password"]',
    'input[name*="passcode" i]',
]
SUBMIT_SELECTORS = [
    'button[type="submit"]',
    'input[type="submit"]',
    "button:has-text('Continue')",
    "button:has-text('View')",
    "button:has-text('Submit')",
]
AGREEMENT_HINT = re.compile(r"\bnda\b|non-disclosure|confidentiality agreement|terms of (use|service)|i agree", re.I)
CDN_ERROR_HINT = re.compile(
    r"request could not be satisfied|generated by cloudfront|access denied|"
    r"request blocked|403 forbidden|error 1\d{3}", re.I
)

LARGEST_IMAGE_JS = """
() => {
  let best = null, bestArea = 0;
  for (const im of Array.from(document.images)) {
    const r = im.getBoundingClientRect();
    const area = r.width * r.height;
    if (area > bestArea && r.width > 200 && r.height > 200) { bestArea = area; best = im; }
  }
  return best ? (best.currentSrc || best.src) : null;
}
"""

ALL_PAGE_IMAGES_JS = """
() => Array.from(document.images)
  .filter(im => im.naturalWidth > 300 && im.naturalHeight > 300)
  .map(im => im.currentSrc || im.src)
  .filter(Boolean)
"""


class AgreementRequired(RuntimeError):
    """The room asks the viewer to accept an agreement (NDA/terms)."""


class GateFailed(RuntimeError):
    """Could not get past the email/passcode gate."""


def log(msg: str) -> None:
    print(msg, flush=True)


def slugify(text: str, fallback: str = "document", maxlen: int = 60) -> str:
    text = re.sub(r"\s+", " ", (text or "").strip())
    text = re.sub(r"[^\w\s.-]", "", text)
    text = re.sub(r"[\s_]+", "-", text).strip("-.")
    return (text[:maxlen].strip("-.") or fallback)


def ext_for(content_type: str | None, url: str) -> str:
    ct = (content_type or "").lower()
    for needle, ext in (("jpeg", ".jpg"), ("jpg", ".jpg"), ("png", ".png"), ("webp", ".webp"), ("gif", ".gif")):
        if needle in ct:
            return ext
    m = re.search(r"\.(jpe?g|png|webp|gif)(?:[?#]|$)", url.lower())
    if m:
        return ".jpg" if m.group(1).startswith("jp") else "." + m.group(1)
    return ".png"


def doc_base(url: str) -> str:
    """Canonical document URL, with query/fragment and trailing junk removed.

    Space-nested documents keep their full /view/s/<space>/d/<doc> path, because
    page_data and the viewer are served relative to it.
    """
    parsed = urlparse(url)
    hit = doc_match(parsed.path)
    path = hit[1] if hit else parsed.path.rstrip("/")
    return f"{parsed.scheme}://{parsed.netloc}{path}"


async def first_visible(page, selectors: list[str], timeout: float = 0.0):
    """Return the first locator among selectors that is actually visible."""
    deadline = time.monotonic() + timeout
    while True:
        for sel in selectors:
            loc = page.locator(sel).first
            try:
                if await loc.is_visible():
                    return loc
            except Exception:
                continue
        if time.monotonic() >= deadline:
            return None
        await asyncio.sleep(0.25)


async def dismiss_banners(page) -> None:
    for sel in (
        "button:has-text('Accept all')",
        "button:has-text('Accept cookies')",
        "button:has-text('Got it')",
        "[aria-label='Close']",
    ):
        try:
            loc = page.locator(sel).first
            if await loc.is_visible():
                await loc.click(timeout=1500)
        except Exception:
            pass


async def check_agreement(page, accept: bool) -> None:
    """DocSend can require accepting an NDA before the room opens.

    Accepting an agreement is a legal act, so by default we stop and let the
    human read and click it themselves rather than clicking through on their
    behalf. --accept-agreements is the explicit opt-in.
    """
    try:
        body = (await page.inner_text("body"))[:6000]
    except Exception:
        return
    if not AGREEMENT_HINT.search(body):
        return
    box = page.locator('input[type="checkbox"]').first
    try:
        visible = await box.is_visible()
    except Exception:
        visible = False
    if not visible:
        return
    if not accept:
        raise AgreementRequired(
            "This room requires accepting an agreement (NDA/terms) before pages load. "
            "Open the URL in your own browser and accept it there (the saved session can then be "
            "reused with --session-state), or re-run with --accept-agreements if you have already "
            "read and agreed to it."
        )
    await box.check(timeout=3000)


async def pass_gate(page, email: str, passcode: str | None, accept_agreements: bool) -> None:
    """Fill the DocSend email/passcode gate if it is showing."""
    await dismiss_banners(page)
    for attempt in range(3):
        field = await first_visible(page, EMAIL_SELECTORS, timeout=3.0 if attempt == 0 else 1.0)
        if field is None:
            await check_agreement(page, accept_agreements)
            return  # already inside
        await field.fill(email)
        pw = await first_visible(page, PASSCODE_SELECTORS)
        if pw is not None:
            if not passcode:
                raise GateFailed(
                    "This link is passcode-protected. Re-run with --passcode '<passcode>'."
                )
            await pw.fill(passcode)
        await check_agreement(page, accept_agreements)
        submit = await first_visible(page, SUBMIT_SELECTORS)
        if submit is None:
            await field.press("Enter")
        else:
            await submit.click()
        try:
            await page.wait_for_load_state("networkidle", timeout=20000)
        except Exception:
            pass
        await asyncio.sleep(1.0)
    if await first_visible(page, EMAIL_SELECTORS) is not None:
        raise GateFailed(
            "Still sitting on the email gate after 3 attempts. The link may require a passcode, "
            "an allow-listed email address, or email verification. Try --headed and complete the "
            "gate by hand, then reuse the session with --session-state."
        )


async def expand_and_scroll(page, rounds: int = 8) -> None:
    """Datarooms hide documents behind collapsed sections and lazy lists."""
    for _ in range(rounds):
        changed = False
        for sel in ('[aria-expanded="false"]', "details:not([open]) > summary"):
            for loc in await page.locator(sel).all():
                try:
                    if await loc.is_visible():
                        await loc.click(timeout=1200)
                        changed = True
                except Exception:
                    continue
        before = await page.evaluate("document.body.scrollHeight")
        await page.keyboard.press("End")
        await page.mouse.wheel(0, 4000)
        await asyncio.sleep(0.6)
        after = await page.evaluate("document.body.scrollHeight")
        if not changed and after == before:
            break


async def collect_candidate_urls(page) -> dict[str, str]:
    """Every plausible document URL on the room page, mapped to a title guess.

    Two sources, because rooms differ in how they render their file list:
    anchors (which conveniently carry the document name as link text), and paths
    embedded in the page's own JavaScript. The second matters because a
    single-page room ships its file list as JSON and renders rows with click
    handlers, so there are no anchors to find at all.
    """
    candidates: dict[str, str] = {}

    for link in await page.locator("a[href]").all():
        try:
            href = await link.get_attribute("href")
            if not href or href.startswith(("mailto:", "tel:", "javascript:", "#")):
                continue
            absolute = urljoin(page.url, href)
            if urlparse(absolute).netloc != urlparse(page.url).netloc:
                continue
            label = (await link.inner_text() or "").strip()
            if not label:
                label = (await link.get_attribute("aria-label")) or (await link.get_attribute("title")) or ""
            label = re.sub(r"\s+", " ", label).strip()
            key = doc_base(absolute)
            if len(label) > len(candidates.get(key, "")):
                candidates[key] = label
        except Exception:
            continue

    try:
        html = await page.content()
    except Exception:
        html = ""
    for path in set(EMBEDDED_PATH_RE.findall(html)):
        key = doc_base(urljoin(page.url, path))
        candidates.setdefault(key, name_near(html, path))

    return candidates


def name_near(html: str, needle: str, window: int = 400) -> str:
    """Best-effort document name from JSON sitting near a path in the page.

    Room payloads look like {"id":"…","name":"Audited Financials.pdf","url":"/view/…"},
    so the name is usually within a few hundred characters of the path.
    """
    idx = html.find(needle)
    if idx < 0:
        return ""
    start = max(0, idx - window)
    chunk = html[start: idx + window]
    pattern = re.compile(r'"(?:name|title|filename|document_name)"\s*:\s*"([^"]{3,120})"')
    # Take the name *closest* to the path, not the first in the window: entries
    # sit next to each other in the payload, so the first match is usually the
    # previous document's name — which silently labels every file identically.
    best, best_distance = "", None
    for m in pattern.finditer(chunk):
        distance = abs((start + m.start()) - idx)
        if best_distance is None or distance < best_distance:
            best, best_distance = m.group(1), distance
    return re.sub(r"\s+", " ", best).strip()


async def is_document(context, url: str, referer: str) -> bool:
    """Ask DocSend whether a URL is a viewable document.

    Cheaper and far more durable than deciding from the URL's shape: page_data/1
    answers with a page image for a document and fails for anything else, so a
    room can invent whatever URL scheme it likes.
    """
    try:
        resp = await context.request.get(
            f"{url}/page_data/1",
            headers={"X-Requested-With": "XMLHttpRequest", "Accept": "application/json", "Referer": referer},
            timeout=20000,
        )
        if not resp.ok:
            return False
        data = await resp.json()
    except Exception:
        return False
    return isinstance(data, dict) and any(
        isinstance(data.get(k), str) for k in ("imageUrl", "imageURL", "image_url", "url", "src")
    )


async def discover_documents(page, source_url: str, context=None, max_probe: int = 80) -> list[dict]:
    """Return [{id, title, url}] for every document reachable from the room."""
    direct = doc_match(urlparse(source_url).path)
    if direct:
        base = doc_base(source_url)
        title = (await page.title() or "").strip()
        return [{"id": direct[0], "title": title or "document", "url": base}]

    await expand_and_scroll(page)
    candidates = await collect_candidate_urls(page)

    # The room's own id, so its self-link is not counted as a document. It shows
    # up as /view/<space> alongside the real /view/<space>/d/<doc> entries.
    space = SPACE_ID_RE.search(urlparse(source_url).path)
    space_id = space.group(1) if space else None

    ordered = sorted(
        candidates.items(),
        key=lambda kv: (0 if doc_match(urlparse(kv[0]).path) else 1, kv[0]),
    )
    log(f"  {len(ordered)} candidate URL(s) to check")

    found: list[dict] = []
    unknown: list[tuple[str, str]] = []
    for url, label in ordered:
        path = urlparse(url).path
        hit = doc_match(path)
        if hit:
            # A recognised shape is accepted on its own evidence. Verification is
            # here to rescue unfamiliar schemes, never to veto known ones — a
            # probe that fails for an unrelated reason must not empty the room.
            if space_id and "/d/" not in path and hit[0] == space_id:
                continue  # the room linking to itself
            found.append({"id": hit[0], "title": label, "url": url})
        else:
            unknown.append((url, label))

    if not found and unknown and context is not None:
        log(f"  no familiar URL shapes; asking DocSend about {len(unknown[:max_probe])} candidate(s)")
        for url, label in unknown[:max_probe]:
            if await is_document(context, url, page.url):
                found.append({"id": url.rstrip("/").rsplit("/", 1)[-1], "title": label, "url": url})
    return found


async def save_page_dump(page, out_root: Path, stem: str) -> list[str]:
    """Save the page as PNG + HTML and return every href on it."""
    out_root.mkdir(parents=True, exist_ok=True)
    try:
        hrefs = await page.evaluate(
            "() => Array.from(document.querySelectorAll('a[href]')).map(a => a.getAttribute('href'))"
        )
    except Exception:
        hrefs = []
    try:
        (out_root / f"{stem}.html").write_text(await page.content(), encoding="utf-8")
        await page.screenshot(path=str(out_root / f"{stem}.png"), full_page=True)
        log(f"  saved {out_root / (stem + '.png')}")
        log(f"  saved {out_root / (stem + '.html')}")
    except Exception as exc:
        log(f"  could not save page dump: {exc}")
    return [h for h in hrefs if h]


async def dump_room_debug(page, out_root: Path, docs: list[dict]) -> None:
    """--debug: show what the room looked like even when discovery 'worked'.

    Finding one document in a room that should hold several is indistinguishable
    from success in the normal output, so this makes the evidence available
    without needing another code change to go looking for it.
    """
    log("\n--debug: room inventory")
    log(f"  final URL:  {page.url}")
    hrefs = await save_page_dump(page, out_root, "room-debug")
    view_links = [h for h in hrefs if "/view/" in h]
    log(f"  links: {len(hrefs)} total, {len(view_links)} pointing at /view/")
    for href in view_links[:40]:
        log(f"    {href}")
    log(f"  matched as documents: {len(docs)}")
    for d in docs:
        log(f"    {d['id']}  {d['title'][:60]!r}")


async def dump_discovery_debug(page, out_root: Path) -> None:
    """Explain a zero-document result instead of just announcing it.

    Discovery failing is nearly always one of three things: the gate never
    actually opened, the room links documents in a shape the matcher rejects, or
    the file list is not made of links at all. Which one it is is obvious from
    the page itself, so save the page and summarise what was on it rather than
    making the user re-run blind with --headed.
    """
    out_root.mkdir(parents=True, exist_ok=True)
    log("\nNo documents found. Collecting diagnostics:")
    log(f"  final URL:   {page.url}")
    try:
        log(f"  page title:  {(await page.title() or '').strip()!r}")
    except Exception:
        pass
    hrefs_all = await save_page_dump(page, out_root, "discovery-debug")

    # A CDN refusal is a wholly different failure from anything DocSend-side, and
    # looks confusingly like an empty room, so name it explicitly.
    try:
        body_text = (await page.inner_text("body"))[:4000]
    except Exception:
        body_text = ""
    if CDN_ERROR_HINT.search(body_text) or CDN_ERROR_HINT.search(await page.title() or ""):
        log("  this is a CDN error page, not a DocSend page — the request was refused")
        log("  before DocSend saw it. Usual causes, in order:")
        log("    1. the link is expired, revoked, or mistyped — open it in your own")
        log("       browser to check; if it fails there too, no capture setting helps")
        log("    2. the CDN is blocking an automated browser — retry with --headed,")
        log("       and/or point --browser-path at your normal Chrome")
        log("    3. the room is restricted by region or network")

    gate_still_up = await first_visible(page, EMAIL_SELECTORS) is not None
    if gate_still_up:
        log("  an email field is STILL visible — the gate did not open, so there was")
        log("  nothing to crawl. The address is probably not the one the link was")
        log("  shared with, or a passcode/verification step is required.")

    view_links = [h for h in hrefs_all if "/view/" in h]
    log(f"  links on page: {len(hrefs_all)} total, {len(view_links)} pointing at /view/")
    for href in view_links[:20]:
        log(f"    {href}")
    if view_links and not gate_still_up:
        log("  those /view/ links exist but none matched the document patterns —")
        log("  paste them back with --doc-url, and report the shapes so the matcher")
        log("  can learn them.")

    log("\nNext: look at discovery-debug.png. If it shows the document list, re-run")
    log("with --doc-url <url> for each document. If it shows a login or error page,")
    log("fix the gate first (--passcode, or --headed to finish it by hand).")


async def get_page_count(page) -> int | None:
    html = await page.content()
    counts = []
    for pattern in PAGE_COUNT_PATTERNS:
        for match in pattern.findall(html):
            try:
                counts.append(int(match))
            except ValueError:
                pass
    try:
        text = await page.inner_text("body")
        for match in re.findall(r"(?:of|/)\s*(\d{1,4})\b", text[:4000]):
            counts.append(int(match))
    except Exception:
        pass
    plausible = [c for c in counts if 1 <= c <= 2000]
    return max(plausible) if plausible else None


async def save_bytes(path: Path, data: bytes) -> None:
    path.write_bytes(data)


async def download(context, url: str, referer: str) -> tuple[bytes, str] | None:
    try:
        resp = await context.request.get(url, headers={"Referer": referer}, timeout=60000)
        if not resp.ok:
            return None
        return await resp.body(), resp.headers.get("content-type", "")
    except Exception:
        return None


async def strategy_page_data(context, base: str, count: int | None, out_dir: Path, max_pages: int) -> list[dict]:
    """DocSend's /page_data/<n> JSON gives a signed URL per page image."""
    pages: list[dict] = []
    limit = count or max_pages
    for n in range(1, limit + 1):
        try:
            resp = await context.request.get(
                f"{base}/page_data/{n}",
                headers={"X-Requested-With": "XMLHttpRequest", "Accept": "application/json", "Referer": base},
                timeout=30000,
            )
            if not resp.ok:
                break
            data = await resp.json()
        except Exception:
            break
        if not isinstance(data, dict):
            break
        img_url = next(
            (data[k] for k in ("imageUrl", "imageURL", "image_url", "url", "src") if isinstance(data.get(k), str)),
            None,
        )
        if not img_url:
            break
        got = await download(context, urljoin(base, img_url), base)
        if got is None:
            break
        body, ctype = got
        name = f"p{n:03d}{ext_for(ctype, img_url)}"
        await save_bytes(out_dir / name, body)
        pages.append({"n": n, "file": name})
        log(f"      page {n}" + (f"/{count}" if count else ""))
    return pages


async def strategy_dom(page, context, base: str, count: int | None, out_dir: Path, max_pages: int) -> list[dict]:
    """Read the images the viewer itself renders, downloading their bytes.

    Handles both scroll-all-pages viewers and one-page-at-a-time viewers.
    """
    limit = count or max_pages
    seen: list[str] = []

    # Scrolling viewer: force lazy images to load, then collect distinct srcs.
    stale = 0
    while len(seen) < limit and stale < 3:
        for src in await page.evaluate(ALL_PAGE_IMAGES_JS):
            if src not in seen:
                seen.append(src)
        before = len(seen)
        await page.mouse.wheel(0, 3000)
        await asyncio.sleep(0.7)
        for src in await page.evaluate(ALL_PAGE_IMAGES_JS):
            if src not in seen:
                seen.append(src)
        stale = stale + 1 if len(seen) == before else 0

    # Paged viewer: step forward and collect the displayed image each time.
    if len(seen) < 2:
        seen = []
        for _ in range(limit):
            src = None
            for _ in range(20):
                src = await page.evaluate(LARGEST_IMAGE_JS)
                if src and src not in seen:
                    break
                await asyncio.sleep(0.4)
            if not src or src in seen:
                break
            seen.append(src)
            advanced = False
            for sel in ('[aria-label*="next" i]', "button.next", ".next-page", "#nextPageButton"):
                loc = page.locator(sel).first
                try:
                    if await loc.is_visible():
                        await loc.click(timeout=2000)
                        advanced = True
                        break
                except Exception:
                    continue
            if not advanced:
                await page.keyboard.press("ArrowRight")
            await asyncio.sleep(0.6)

    pages: list[dict] = []
    for idx, src in enumerate(seen[:limit], start=1):
        got = await download(context, src, base)
        if got is None:
            continue
        body, ctype = got
        name = f"p{idx:03d}{ext_for(ctype, src)}"
        await save_bytes(out_dir / name, body)
        pages.append({"n": idx, "file": name})
        log(f"      page {idx} (dom)")
    return pages


async def strategy_screenshot(page, count: int | None, out_dir: Path, max_pages: int) -> list[dict]:
    """Screenshot the rendered page element. Works even for canvas viewers."""
    limit = count or max_pages
    pages: list[dict] = []
    for n in range(1, limit + 1):
        target = None
        for sel in ("canvas", ".preso-container", "img", "main"):
            loc = page.locator(sel).first
            try:
                if await loc.is_visible():
                    target = loc
                    break
            except Exception:
                continue
        shot = await (target.screenshot(type="png") if target else page.screenshot(type="png", full_page=False))
        name = f"p{n:03d}.png"
        await save_bytes(out_dir / name, shot)
        pages.append({"n": n, "file": name})
        log(f"      page {n} (screenshot)")
        if n == limit:
            break
        await page.keyboard.press("ArrowRight")
        await asyncio.sleep(0.8)
    return pages


async def capture_document(
    context, doc: dict, out_root: Path, args, index: int, total: int
) -> dict:
    page = await context.new_page()
    record = {**doc, "dir": "", "pages": [], "page_count": 0, "strategy": None, "error": None}
    sub = out_root / f"{index:02d}-{slugify(doc['id'])}"
    try:
        await page.goto(doc["url"], wait_until="domcontentloaded", timeout=args.timeout)
        await pass_gate(page, args.email, args.passcode, args.accept_agreements)
        try:
            await page.wait_for_load_state("networkidle", timeout=15000)
        except Exception:
            pass

        # Name the folder after the document. A title harvested from the room is
        # preferred, but rooms that render their list in JavaScript give none, so
        # fall back to the viewer's own <title> — which beats a bare id.
        label = (doc.get("title") or "").strip()
        if not label or label == doc["id"]:
            # Drop a trailing site-name suffix ("… — DocSend"). The separator is
            # matched loosely because it survives as mojibake when a page omits
            # its charset, and a real document name never ends in "DocSend".
            raw = (await page.title() or "").strip()
            label = re.sub(r"\s*\S{0,4}\s*DocSend\s*$", "", raw, flags=re.I).strip() or doc["id"]
        record["title"] = label
        log(f"  [{index}/{total}] {label}")
        sub = out_root / f"{index:02d}-{slugify(label, doc['id'])}"
        if not args.dry_run:
            sub.mkdir(parents=True, exist_ok=True)
        record["dir"] = sub.name

        count = await get_page_count(page)
        record["reported_page_count"] = count
        log(f"      pages reported: {count if count else 'unknown'}")
        if args.dry_run:
            return record

        base = doc_base(page.url)
        pages: list[dict] = []
        candidates = [
            ("page_data", lambda: strategy_page_data(context, base, count, sub, args.max_pages)),
            ("dom", lambda: strategy_dom(page, context, base, count, sub, args.max_pages)),
            ("screenshot", lambda: strategy_screenshot(page, count, sub, args.max_pages)),
        ]
        enabled = [c for c in candidates if args.strategy in ("auto", c[0])]
        for position, (name, runner) in enumerate(enabled):
            pages = await runner()
            # Accept the result when it looks complete, or when nothing better
            # is likely: a short doc with no reported count is still valid.
            if pages and (count is None or len(pages) >= count):
                record["strategy"] = name
                break
            if pages:
                more = position + 1 < len(enabled)
                log(f"      {name} got {len(pages)}/{count} pages"
                    + (", trying next strategy" if more else ""))
                best = record.get("pages") or []
                if len(pages) > len(best):
                    record["pages"], record["strategy"] = pages, name
                pages = []
        if pages:
            record["pages"], record["strategy"] = pages, record["strategy"] or "unknown"
        record["page_count"] = len(record["pages"])
        if count and record["page_count"] < count:
            record["error"] = f"captured {record['page_count']} of {count} reported pages"
            log(f"      WARNING: {record['error']}")
    except Exception as exc:
        record["error"] = f"{type(exc).__name__}: {exc}"
        log(f"      ERROR: {record['error']}")
    finally:
        await page.close()
    return record


async def realistic_user_agent(browser) -> str | None:
    """This browser's own UA with the headless marker removed.

    Headless Chromium advertises "HeadlessChrome/<ver>", and CDN/WAF rules in
    front of document hosts routinely reject it — the symptom is a CDN error
    page instead of the site, before any login even happens. Reading the real UA
    and dropping that one token keeps the version accurate as the browser is
    updated, which a hardcoded string would not.
    """
    try:
        page = await browser.new_page()
        ua = await page.evaluate("() => navigator.userAgent")
        await page.close()
    except Exception:
        return None
    if not ua:
        return None
    return ua.replace("HeadlessChrome", "Chrome") if "Headless" in ua else None


async def main_async(args) -> int:
    out_root = Path(args.out).expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    async with async_playwright() as pw:
        # Honour an explicitly provided Chromium when the environment ships one
        # that does not match the installed Playwright's expected build.
        exe = args.browser_path or os.environ.get("PLAYWRIGHT_CHROMIUM_EXECUTABLE")
        browser = await pw.chromium.launch(
            headless=not args.headed, **({"executable_path": exe} if exe else {})
        )
        state = Path(args.session_state).expanduser() if args.session_state else None
        user_agent = args.user_agent or await realistic_user_agent(browser)
        context = await browser.new_context(
            user_agent=user_agent,
            locale="en-US",
            viewport={"width": 1600, "height": 1200},
            device_scale_factor=args.scale,
            storage_state=str(state) if state and state.exists() else None,
        )
        context.set_default_timeout(args.timeout)
        page = await context.new_page()
        log(f"Opening {args.url}")
        await page.goto(args.url, wait_until="domcontentloaded", timeout=args.timeout)
        await pass_gate(page, args.email, args.passcode, args.accept_agreements)
        try:
            await page.wait_for_load_state("networkidle", timeout=20000)
        except Exception:
            pass

        room_title = (await page.title() or "dataroom").strip()
        if args.doc_url:
            docs = []
            for url in args.doc_url:
                base = doc_base(url)
                hit = doc_match(urlparse(base).path)
                label = hit[0] if hit else base
                docs.append({"id": label, "title": label, "url": base})
        else:
            docs = await discover_documents(page, args.url, context)
        if args.only:
            needle = args.only.lower()
            docs = [d for d in docs if needle in d["title"].lower() or needle == d["id"]]

        # A space whose id also appears as /view/<space-id> is the room linking to
        # itself. Counting that as a document looks like success while the real
        # file list went unfound, so say so rather than quietly capturing it.
        space = re.search(r"/view/s/([A-Za-z0-9_-]+)", urlparse(args.url).path)
        if space and not args.doc_url:
            selfish = [d for d in docs if d["id"] == space.group(1)]
            if selfish:
                log(f"\nWARNING: {len(selfish)} 'document' has the same id as the space itself")
                log("  (%s) — that is usually the room's own link, not a file." % space.group(1))
                log("  If the room shows more documents than were found, re-run with --debug")
                log("  and check room-debug.png, or pass each document's URL via --doc-url.")

        # A title shared by several documents is worse than no title at all: the
        # viewer knows its own name, so let the per-document capture ask it.
        harvested = [d["title"] for d in docs if d["title"]]
        for d in docs:
            if d["title"] and harvested.count(d["title"]) > 1:
                d["title"] = ""

        if args.debug:
            await dump_room_debug(page, out_root, docs)

        if not docs:
            await dump_discovery_debug(page, out_root)
            await page.close()
            await browser.close()
            return 2
        await page.close()

        log(f"Found {len(docs)} document(s) in '{room_title}'")
        sem = asyncio.Semaphore(max(1, args.concurrency))

        async def guarded(doc, idx):
            async with sem:
                return await capture_document(context, doc, out_root, args, idx, len(docs))

        records = await asyncio.gather(*(guarded(d, i) for i, d in enumerate(docs, start=1)))

        if state:
            state.parent.mkdir(parents=True, exist_ok=True)
            await context.storage_state(path=str(state))
            log(f"Session saved to {state}")
        await browser.close()

    manifest = {
        "source_url": args.url,
        "room_title": room_title,
        "captured_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "viewer_email": args.email,
        "documents": list(records),
    }
    (out_root / "manifest.json").write_text(json.dumps(manifest, indent=2))

    total_pages = sum(r["page_count"] for r in records)
    failed = [r for r in records if r.get("error")]
    log("")
    if args.dry_run:
        log(f"Dry run — {len(records)} document(s) found, nothing downloaded:")
        for r in records:
            log(f"  {r['title']}: {r.get('reported_page_count') or 'unknown'} pages  ({r['url']})")
        log(f"Manifest: {out_root / 'manifest.json'}")
        return 0
    log(f"Captured {total_pages} pages from {len(records)} document(s) into {out_root}")
    log(f"Manifest: {out_root / 'manifest.json'}")
    if failed:
        log(f"{len(failed)} document(s) need attention:")
        for r in failed:
            log(f"  - {r['title']}: {r['error']}")
    return 1 if failed and total_pages == 0 else 0


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("url", help="DocSend room, space, or /view/<id> URL (also used to pass the gate)")
    p.add_argument("--email", required=True, help="Email to enter at the DocSend gate")
    p.add_argument("--passcode", default=None, help="Passcode, if the link is protected")
    p.add_argument("--out", default="docsend-capture", help="Output directory (default: ./docsend-capture)")
    p.add_argument("--doc-url", action="append", default=[], help="Capture only these /view/<id> URLs (repeatable)")
    p.add_argument("--only", default=None, help="Only documents whose title contains this text")
    p.add_argument("--strategy", choices=["auto", "page_data", "dom", "screenshot"], default="auto")
    p.add_argument("--scale", type=float, default=2.0, help="Device scale factor for screenshots (default: 2)")
    p.add_argument("--max-pages", type=int, default=400, help="Safety cap per document (default: 400)")
    p.add_argument("--concurrency", type=int, default=2, help="Documents captured in parallel (default: 2)")
    p.add_argument("--timeout", type=int, default=45000, help="Per-navigation timeout in ms (default: 45000)")
    p.add_argument("--headed", action="store_true", help="Show the browser (use to solve gates by hand)")
    p.add_argument("--browser-path", default=None,
                   help="Chromium executable to drive (or set PLAYWRIGHT_CHROMIUM_EXECUTABLE)")
    p.add_argument("--user-agent", default=None,
                   help="Override the browser user agent (default: this browser's UA, de-headlessed)")
    p.add_argument("--session-state", default=None, help="Path to save/reuse cookies between runs")
    p.add_argument("--accept-agreements", action="store_true", help="Tick an NDA/terms checkbox if present")
    p.add_argument("--dry-run", action="store_true", help="List documents and page counts without downloading")
    p.add_argument("--debug", action="store_true",
                   help="Also dump the room page (room-debug.png/.html) and every link found")
    return p.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    try:
        return asyncio.run(main_async(args))
    except (AgreementRequired, GateFailed) as exc:
        log(f"\nStopped: {exc}")
        return 3
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
